enhancements

diff --git a/dotfiles/bin/g_clean_build_with_del_ignored b/dotfiles/bin/g_clean_build_with_del_ignored
--- a/dotfiles/bin/g_clean_build_with_del_ignored
+++ b/dotfiles/bin/g_clean_build_with_del_ignored
@@ -1,9 +1,60 @@
 #!/usr/bin/env bash
 ################################################################### SETUP ########################################################################
-# shellcheck source=.dotfiles/lib/common.sh disable=SC2016,SC1091
-if test -e "${DOTFILES}/lib/common.sh"; then source "${DOTFILES}/lib/common.sh"; else echo '"${DOTFILES}/lib/common.sh" does not exist - resolved to: '"${DOTFILES}/lib/common.sh" && exit 1; fi
-set -o errexit -o errtrace -o nounset
+if ! _SCRIPT_DIR="$(get_script_dir "${BASH_SOURCE[0]}")"; then echo "Error while running: _SCRIPT_DIR=\"\$(get_script_dir \"${BASH_SOURCE[0]}\")\"" && exit 1; fi
+# shellcheck source=./.gradle_command_defaults.sh
+source "${_SCRIPT_DIR}/.gradle_command_defaults.sh" || exit 1
 ##################################################################################################################################################
+
+################################################################### USAGE ########################################################################
+_SCRIPT_NAME="$(basename "$0")"
+
+function _usage() {
+  local SYNOP_INDENT
+  SYNOP_INDENT="$(head -c "$(echo -n "${_SCRIPT_NAME}" | wc -c)" </dev/zero | tr '\0' " ")"
+
+  cat <<EOF
+NAME
+       ${_SCRIPT_NAME}
+
+SYNOPSIS
+       ${_SCRIPT_NAME} [--cd-to-git-base-dir] <gradle_arg>...
+       ${SYNOP_INDENT} [--help] [--debug] [--verbose]
+
+EXAMPLES
+       ${_SCRIPT_NAME}
+EOF
+}
+##################################################################################################################################################
+
+################################################################# FILTERARGS #####################################################################
+PASSTHROUGH_ARGS=()
+while test $# -gt 0; do
+  case "$1" in
+    -h | --help)
+      _usage
+      exit 0
+      ;;
+    --debug)
+      export debug_mode=true
+      shift
+      ;;
+    --verbose)
+      export verbose=true
+      shift
+      ;;
+    --cd-to-git-base-dir)
+      cd_to_git_base_dir=true
+      shift
+      ;;
+    *)
+      PASSTHROUGH_ARGS+=("$1")
+      shift
+      ;;
+  esac
+done
+##################################################################################################################################################
+
+cd_to_git_base_dir_if_needed
 
 mapfile -t delete_ignored < <(git ignored --directory | pcregrep '(^(\.gradle|build)/$|/(\.gradle|build)/$)')
 if test "${#delete_ignored[@]}" -ne 0; then
diff --git a/dotfiles/bin/g_deps b/dotfiles/bin/g_deps
--- a/dotfiles/bin/g_deps
+++ b/dotfiles/bin/g_deps
@@ -1,10 +1,8 @@
 #!/usr/bin/env bash
 ################################################################### SETUP ########################################################################
-# shellcheck source=.dotfiles/lib/common.sh disable=SC2016,SC1091
-if test -e "${DOTFILES}/lib/common.sh"; then source "${DOTFILES}/lib/common.sh"; else echo '"${DOTFILES}/lib/common.sh" does not exist - resolved to: '"${DOTFILES}/lib/common.sh" && exit 1; fi
-# shellcheck disable=SC1091
-source "${DOTFILES}/gradle_functions.sh"
-set -o errexit -o errtrace -o nounset
+if ! _SCRIPT_DIR="$(get_script_dir "${BASH_SOURCE[0]}")"; then echo "Error while running: _SCRIPT_DIR=\"\$(get_script_dir \"${BASH_SOURCE[0]}\")\"" && exit 1; fi
+# shellcheck source=./.gradle_command_defaults.sh
+source "${_SCRIPT_DIR}/.gradle_command_defaults.sh" || exit 1
 ##################################################################################################################################################
 
 open="${open:-true}"
@@ -25,7 +23,7 @@ NAME
        ${_SCRIPT_NAME}
 
 SYNOPSIS
-       ${_SCRIPT_NAME} [--config <configuration>...] [--no-open | --open] [--standard-configurations] <other_args>
+       ${_SCRIPT_NAME} [--cd-to-git-base-dir] [--config <configuration>...] [--no-open | --open] [--standard-configurations] <other_arg>...
        ${SYNOP_INDENT} [--help] [--debug] [--verbose]
 
 EXAMPLES
@@ -48,6 +46,10 @@ while test $# -gt 0; do
       ;;
     --verbose)
       export verbose=true
+      shift
+      ;;
+    --cd-to-git-base-dir)
+      cd_to_git_base_dir=true
       shift
       ;;
     --config)
@@ -75,7 +77,9 @@ while test $# -gt 0; do
 done
 ##################################################################################################################################################
 
-if check_true "${standard_configurations-}"; then
+cd_to_git_base_dir_if_needed
+
+if test "${standard_configurations-}" = "true"; then
   configurations+=(
     compileClasspath
     runtimeClasspath
@@ -113,7 +117,7 @@ fi
 out_files=("$out_file")
 
 function run_g_task_for_configs() {
-  local all_args=("${gradle_args[@]}" "$task")
+  local all_args=("${gradle_args[@]}" "$task") all_args_with_config
   if test "${#configurations[@]}" -eq 0; then
     log_with_title_sep g "${all_args[@]}"
     g "${all_args[@]}"
diff --git a/dotfiles/bin/g_deps_configurations b/dotfiles/bin/g_deps_configurations
--- a/dotfiles/bin/g_deps_configurations
+++ b/dotfiles/bin/g_deps_configurations
@@ -1,6 +1,8 @@
 #!/usr/bin/env bash
 ################################################################### SETUP ########################################################################
-set -o errexit -o errtrace -o nounset
+if ! _SCRIPT_DIR="$(get_script_dir "${BASH_SOURCE[0]}")"; then echo "Error while running: _SCRIPT_DIR=\"\$(get_script_dir \"${BASH_SOURCE[0]}\")\"" && exit 1; fi
+# shellcheck source=./.gradle_command_defaults.sh
+source "${_SCRIPT_DIR}/.gradle_command_defaults.sh" || exit 1
 ##################################################################################################################################################
 
 ################################################################### USAGE ########################################################################
@@ -15,7 +17,7 @@ NAME
        ${_SCRIPT_NAME}
 
 SYNOPSIS
-       ${_SCRIPT_NAME} [--unique] <args>...
+       ${_SCRIPT_NAME} [--cd-to-git-base-dir] [--unique] <gradle_arg>...
        ${SYNOP_INDENT} [--help] [--debug] [--verbose]
 
 EXAMPLES
@@ -40,6 +42,10 @@ while test $# -gt 0; do
       export verbose=true
       shift
       ;;
+    --cd-to-git-base-dir)
+      cd_to_git_base_dir=true
+      shift
+      ;;
     --unique)
       unique=true
       shift
@@ -52,8 +58,10 @@ while test $# -gt 0; do
 done
 ##################################################################################################################################################
 
+cd_to_git_base_dir_if_needed
+
 function get_all_configs() {
-  g projects --info | pcregrep --om-separator=' ' -o2 -o1 "Applying dependency management to configuration '(.*?)' in project '(.*?)'"
+  g projects --info "${PASSTHROUGH_ARGS[@]}" | pcregrep --om-separator=' ' -o2 -o1 "Applying dependency management to configuration '(.*?)' in project '(.*?)'"
 }
 
 if test "${unique-}" = "true"; then
diff --git a/dotfiles/bin/g_resolve_and_lock_clean b/dotfiles/bin/g_resolve_and_lock_clean
--- a/dotfiles/bin/g_resolve_and_lock_clean
+++ b/dotfiles/bin/g_resolve_and_lock_clean
@@ -1,6 +1,8 @@
 #!/usr/bin/env bash
 ################################################################### SETUP ########################################################################
-set -o errexit -o errtrace -o nounset
+if ! _SCRIPT_DIR="$(get_script_dir "${BASH_SOURCE[0]}")"; then echo "Error while running: _SCRIPT_DIR=\"\$(get_script_dir \"${BASH_SOURCE[0]}\")\"" && exit 1; fi
+# shellcheck source=./.gradle_command_defaults.sh
+source "${_SCRIPT_DIR}/.gradle_command_defaults.sh" || exit 1
 ##################################################################################################################################################
 
 ################################################################### USAGE ########################################################################
@@ -15,7 +17,7 @@ NAME
        ${_SCRIPT_NAME}
 
 SYNOPSIS
-       ${_SCRIPT_NAME} [--cd-to-git-base-dir]
+       ${_SCRIPT_NAME} [--cd-to-git-base-dir] <gradle_arg>...
        ${SYNOP_INDENT} [--help] [--debug] [--verbose]
 
 EXAMPLES
@@ -52,9 +54,7 @@ while test $# -gt 0; do
 done
 ##################################################################################################################################################
 
-if test "${cd_to_git_base_dir-}" = "true"; then
-  cd "$(git base-dir)"
-fi
+cd_to_git_base_dir_if_needed
 
 git ls-files -- ':(glob)**/*.lockfile' | xargs rm -fv
 g_resolve_and_lock clean "${PASSTHROUGH_ARGS[@]}"
